# syntax=docker/dockerfile:1

FROM python:3.10.2-slim-bullseye

WORKDIR /app
ENV FLASK_APP=server.py
ENV FLASK_RUN_HOST=0.0.0.0

RUN pip3 install flask
EXPOSE 5000
COPY server.py .

CMD [ "flask", "run"]