# syntax=docker/dockerfile:1

FROM python:3.10.2-slim-bullseye

WORKDIR /app

RUN pip3 install paho-mqtt

RUN pip install numpy

COPY publisher.py .

COPY 100B .

COPY 10KB .

COPY 1MB .

COPY 10MB .

CMD [ "python3", "publisher.py"]